version: '3.8'

services:

  grafana:
    restart: always
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    networks:
      - net-iam

volumes:
  postgres_data:
    name: keycloak_postgres_data

networks:
  net-iam:
    external: true
    name: net-iam
