services:
  ocis:
    image: owncloud/ocis:latest
    networks:
      - ocis-net
    entrypoint: ["/bin/sh"]
    command: ["-c", "ocis init || true; exec ocis server"]

    environment:
      OCIS_URL: https://${OCIS_DOMAIN}
      OCIS_LOG_LEVEL: info

      # OIDC (Keycloak integration)
      OCIS_OIDC_ISSUER: https://${KEYCLOAK_DOMAIN}/realms/oCIS
      WEB_OIDC_CLIENT_ID: web
      WEB_OIDC_SCOPE: "openid profile email acr"

      PROXY_ROLE_ASSIGNMENT_DRIVER: oidc
      PROXY_AUTOPROVISION_ACCOUNTS: "true"

      PROXY_USER_OIDC_CLAIM: preferred_username
      PROXY_USER_CS3_CLAIM: username

      OCIS_EXCLUDE_RUN_SERVICES: idp
    volumes:
      - ocis-config:/etc/ocis
      - ocis-data:/var/lib/ocis
    networks:
      - net_iam

networks:
  net_iam:
    external: true
    name: net-iam

volumes:
  ocis-config:
  ocis-data: