services:
  owncloud_mariadb:
    image: mariadb:10.11
    container_name: owncloud_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${OWNCLOUD_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${OWNCLOUD_DB_USERNAME}
      MYSQL_PASSWORD: ${OWNCLOUD_DB_PASSWORD}
      MYSQL_DATABASE: ${OWNCLOUD_DB_NAME}
      MARIADB_AUTO_UPGRADE: "1"
    command: ["--max-allowed-packet=128M", "--innodb-log-file-size=64M"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=${OWNCLOUD_MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - owncloud_mysql_data:/var/lib/mysql
    networks:
      - net_iam

  owncloud_redis:
    image: redis:6
    container_name: owncloud_redis
    restart: always
    command: ["--databases", "1"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - owncloud_redis_data:/data
    networks:
      - net_iam

  owncloud_server:
    image: owncloud/server:${OWNCLOUD_VERSION}
    container_name: owncloud_server
    restart: always
    ports:
      - "${OWNCLOUD_PORT}:8080"
    depends_on:
      - owncloud_mariadb
      - owncloud_redis
    environment:
      OWNCLOUD_DOMAIN: ${OWNCLOUD_DOMAIN}
      OWNCLOUD_TRUSTED_DOMAINS: ${OWNCLOUD_TRUSTED_DOMAINS}
      OWNCLOUD_DB_TYPE: mysql
      OWNCLOUD_DB_NAME: ${OWNCLOUD_DB_NAME}
      OWNCLOUD_DB_USERNAME: ${OWNCLOUD_DB_USERNAME}
      OWNCLOUD_DB_PASSWORD: ${OWNCLOUD_DB_PASSWORD}
      OWNCLOUD_DB_HOST: owncloud_mariadb
      OWNCLOUD_ADMIN_USERNAME: ${OWNCLOUD_ADMIN_USERNAME}
      OWNCLOUD_ADMIN_PASSWORD: ${OWNCLOUD_ADMIN_PASSWORD}
      OWNCLOUD_MYSQL_UTF8MB4: "true"
      OWNCLOUD_REDIS_ENABLED: "true"
      OWNCLOUD_REDIS_HOST: owncloud_redis
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - owncloud_files:/mnt/data
    networks:
      - net_iam

networks:
  net_iam:
    external: true
    name: net-iam

volumes:
  owncloud_mysql_data:
  owncloud_redis_data:
  owncloud_files: