services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "Nova Inc."
      LDAP_DOMAIN: "nova.org"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_READONLY_USER: "false"
      LDAP_OPENLDAP_UID: "1000"
      LDAP_OPENLDAP_GID: "1010"
      LDAP_BACKEND: "mdb"
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_DH_PARAM_FILENAME: "dhparam.pem"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_VERIFY_CLIENT: "demand"
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
    volumes:
      - ldap-data:/var/lib/ldap
      - ldap-config:/etc/ldap/slapd.d
      - ldap-certs:/container/service/slapd/assets/certs/
    ports:
      - "389:389"
      - "636:636"
    domainname: "nova.org"
    hostname: "ldap"

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8080:80"
    depends_on:
      - openldap

  postgresql:
    image: postgres:15-alpine
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: privacyidea
      POSTGRES_USER: privacyidea
      POSTGRES_PASSWORD: privacyidea
    volumes:
      - postgres_data:/var/lib/postgresql/data

  privacyidea:
    image: kheeklab/privacyidea:dev
    container_name: privacyidea
    ports:
      - "9000:8080"
    environment:
      PI_DB_VENDOR: postgresql
      PI_DB_NAME: privacyidea
      PI_DB_HOST: postgresql
      PI_DB_PORT: 5432
      PI_DB_USER: privacyidea
      PI_DB_PASSWORD: privacyidea

      PI_SECRET_KEY: suppersecretkey
      PI_PEPPER: secretworduseforadminencrypt
      PI_PAGE_TITLE: privacyIDEA

      PI_ADMIN_USER: admin
      PI_ADMIN_PASSWORD: admin123
    depends_on:
      - postgresql


volumes:
  ldap-data:
  ldap-config:
  ldap-certs:
  postgres_data: