services:
 
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    labels:
      - "traefik.enable=true"
      # Path-based routing
      - "traefik.http.routers.grafana.rule=Host(`grafana.nova.io`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      # Add the following label
      - "traefik.http.routers.grafana.tls=true"

    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    networks:
      - proxy-net


networks:
  proxy-net:
    external: true
    name: proxy-net